version = "Two"
use_small_heuristics = "Max"
binop_separator = "Back"
combine_control_expr = false
condense_wildcard_suffixes = true
fn_args_layout = "Compressed"
brace_style = "PreferSameLine"
where_single_line = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
max_width = 80
normalize_comments = true
reorder_impl_items = true
trailing_comma = "Never"
trailing_semicolon = false
use_field_init_shorthand = true
use_try_shorthand = true
overflow_delimited_expr = true
edition = "2021"
normalize_doc_attributes = false
