[toolchain]
channel = "nightly"
components = ["rustfmt", "clippy", "llvm-tools-preview"]
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
  "x86_64-pc-windows-gnu",
]
