_default:
  @just --list

# Synthesize, place-and-route and compile this project.
synth:
  yosys -p "synth_ice40 -top blinky -json blinky.json" blinky.v
  nextpnr-ice40 -r --hx8k --json blinky.json --package cb132 --asc blinky.asc --opt-timing --pcf ../icewerx.pcf
  icepack blinky.asc blinky.bin

# Flash the device.
flash DEVICE: synth
  iceworx flash --device {{DEVICE}} ./blinky.bin

# Clean all-the-things
clean:
  @rm -f *.asc *.bin *.vcd *.json
