name: Cross
on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        required: true
      target:
        type: string
        required: true
      arch:
        type: string
        required: true
jobs:
  build:
    name: Cross-build static binary
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Install dependencies
        run: |
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo apt-get update
          echo "deb [arch=${{ inputs.arch }}] http://ports.ubuntu.com/ubuntu-ports focal main universe" | sudo tee -a /etc/apt/sources.list
          echo "deb [arch=${{ inputs.arch }}] http://ports.ubuntu.com/ubuntu-ports focal-updates main universe" | sudo tee -a /etc/apt/sources.list
          sudo apt update
          sudo dpkg --add-architecture ${{ inputs.arch }}
          sudo apt-get install -y libudev-dev musl-tools pkg-config "libgcc-s1:${{ inputs.arch }}" "libc6:${{ inputs.arch }}" "libudev-dev:${{ inputs.arch }}" "libftdi1-dev:${{ inputs.arch }}" "libusb-1.0-0-dev:${{ inputs.arch }}" gcc-arm-linux-gnueabihf pkg-config-arm-linux-gnueabihf gcc-aarch64-linux-gnu pkg-config-aarch64-linux-gnu
          echo "PKG_CONFIG_ALLOW_SYSTEM_LIBS=0" >> $GITHUB_ENV
          echo "PKG_CONFIG_DIR=/opt/" >> $GITHUB_ENV
          echo "PKG_CONFIG_LIBDIR=/opt/usr/lib/pkgconfig:/opt/usr/share/pkgconfig" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
          if [[ ${{ inputs.arch }} == arm64 ]]; then
            echo "PKG_CONFIG_PATH=/usr/lib/${{ steps.findandreplace.outputs.value }}/pkgconfig" >> $GITHUB_ENV
            echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=${{ steps.findandreplace.outputs.value }}-gcc" >> $GITHUB_ENV
          fi
          if [[ ${{ inputs.arch }} == armhf ]]; then
            echo "PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig" >> $GITHUB_ENV
            echo "CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc" >> $GITHUB_ENV
          fi
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup rust toolchain
        run: rustup show
      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all --target ${{ inputs.target }}
          use-cross: true
      - name: Bundle release
        uses: papeloto/action-zip@v1
        with:
          files: target/${{ inputs.target }}/release/iceworx
          recursive: true
          dest: iceworx-${{ inputs.target }}.zip
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: iceworx-${{ inputs.target }}.zip
          tag: ${{ github.ref }}
          overwrite: true
