name: Package
on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        required: true
      target:
        type: string
        required: true
      ext:
        default: ""
        type: string
jobs:
  build:
    name: Build static binary
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libusb-1.0-0-dev libftdi1-dev libudev-dev
        if: ${{ inputs.runs_on == 'ubuntu-latest' }}
      - name: Install dependencies
        run: brew install libftdi
        if: ${{ inputs.runs_on == 'macos-latest' }}
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup rust toolchain
        run: rustup show
      - name: Restore cargo cache
        uses: Swatinem/rust-cache@v1
      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all --target ${{ inputs.target }}
      - name: Bundle release
        uses: papeloto/action-zip@v1
        with:
          files: target/${{ inputs.target }}/release/iceworx${{ inputs.ext }}
          recursive: false
          dest: iceworx-${{ inputs.target }}.zip
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: iceworx-${{ inputs.target }}.zip
          tag: ${{ github.ref }}
          overwrite: true
