name: Package
on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        required: true
      target:
        type: string
        required: true
      ext:
        default: ""
        required: false
        type: string
      zip:
        default: false
        required: false
        type: boolean
jobs:
  build:
    name: Build static binary
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y musl-tools libusb-1.0-0-dev libftdi1-dev libudev-dev
        if: ${{ inputs.runs_on == 'ubuntu-latest' }}
      - name: Install dependencies
        run: brew install libftdi
        if: ${{ inputs.runs_on == 'macos-latest' }}
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup rust toolchain
        run: rustup show
      - name: Restore cargo cache
        uses: Swatinem/rust-cache@v1
      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all --target ${{ inputs.target }}
      - name: Bundle release
        if: ${{ inputs.zip != true }}
        run: tar -jcvf iceworx-${{ steps.branch-name.outputs.tag }}-${{ inputs.target }}.tar.gz -C target/${{ inputs.target }}/release/ iceworx${{ inputs.ext }}
      - name: Bundle release
        if: ${{ inputs.zip == true }}
        uses: papeloto/action-zip@v1
        with:
          files: target/${{ inputs.target }}/release/iceworx${{ inputs.ext }}
          recursive: true
          dest: iceworx-${{ steps.branch-name.outputs.tag }}-${{ inputs.target }}.zip
      - name: Upload release
        if: ${{ inputs.zip != true }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: iceworx-${{ steps.branch-name.outputs.tag }}-${{ inputs.target }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload release
        if: ${{ inputs.zip == true }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: iceworx-${{ steps.branch-name.outputs.tag }}-${{ inputs.target }}.zip
          tag: ${{ github.ref }}
          overwrite: true
