name: Release
on:
  release:
    types:
      - created

jobs:
  x86_64-unknown-linux-gnu:
    uses: ./.github/workflows/package.yml
    with:
      runs_on: ubuntu-latest
      target: x86_64-unknown-linux-gnu
  arch64-apple-darwin:
    uses: ./.github/workflows/package.yml
    with:
      runs_on: macos-latest
      target: aarch64-apple-darwin
  x86_64-apple-darwin:
    uses: ./.github/workflows/package.yml
    with:
      runs_on: macos-latest
      target: x86_64-apple-darwin
  x86_64-pc-windows-msvc:
    uses: ./.github/workflows/package.yml
    with:
      runs_on: windows-latest
      target: x86_64-pc-windows-msvc
      ext: .exe
