name: Release
on:
  release:
    types:
      - created
      - edited

jobs:
  # Linux
  x86_64-unknown-linux-gnu:
    uses: ./.github/workflows/package.yml
    with:
      runs_on: ubuntu-latest
      target: x86_64-unknown-linux-gnu
  x86_64-unknown-linux-musl:
    uses: ./.github/workflows/package.yml
    with:
      runs_on: ubuntu-latest
      target: x86_64-unknown-linux-musl
  aarch64-unknown-linux-gnu:
    uses: ./.github/workflows/cross.yml
    with:
      runs_on: ubuntu-latest
      target: aarch64-unknown-linux-gnu
      arch: arm64
  aarch64-unknown-linux-musl:
    uses: ./.github/workflows/cross.yml
    with:
      runs_on: ubuntu-latest
      target: aarch64-unknown-linux-musl
      arch: arm64
      use-cross: true
  armv7-unknown-linux-gnueabihf:
    uses: ./.github/workflows/cross.yml
    with:
      runs_on: ubuntu-20.04
      target: armv7-unknown-linux-gnueabihf
      arch: armhf
  armv7-unknown-linux-musleabihf:
    uses: ./.github/workflows/cross.yml
    with:
      runs_on: ubuntu-20.04
      target: armv7-unknown-linux-musleabihf
      arch: armhf
      use-cross: true

  # macOS
  aarch64-apple-darwin:
    uses: ./.github/workflows/package.yml
    with:
      runs_on: macos-latest
      target: aarch64-apple-darwin
      zip: true
  x86_64-apple-darwin:
    uses: ./.github/workflows/package.yml
    with:
      runs_on: macos-latest
      target: x86_64-apple-darwin
      zip: true

  # Windows
  x86_64-pc-windows-msvc:
    uses: ./.github/workflows/package.yml
    with:
      runs_on: windows-latest
      target: x86_64-pc-windows-msvc
      ext: .exe
      zip: true
  x86_64-pc-windows-gnu:
    uses: ./.github/workflows/package.yml
    with:
      runs_on: windows-latest
      target: x86_64-pc-windows-gnu
      ext: .exe
      zip: true
