name: Release
on:
  release:
    types:
      - created

jobs:
  release:
    strategy:
      fail-fast: false
    matrix:
      include:
        - runs_on: ubuntu-latest
          target: x86_64-unknown-linux-gnu
        - runs_on: macos-latest
          target: aarch64-apple-darwin
        - runs_on: macos-latest
          target: x86_64-apple-darwin
        - runs_on: windows-latest
          target: x86_64-pc-windows-msvc
          ext: ".exe"
        - runs_on: windows-latest
          target: x86_64-pc-windows-gnu
          ext: ".exe"
    runs-on: ${{ matrix.runs_on }}
    name: ${{ matrix.target }}
    uses: ./.github/workflows/package.yml
    with:
      runs_on: ${{ matrix.runs_on }}
      target: ${{ matrix.target }}
      ext: ${{ matrix.ext }}
