name: Release
on:
  release:
    types:
      - created
      - edited

jobs:
  x86_64-unknown-linux-gnu:
    uses: ./.github/workflows/package.yml
    with:
      runs_on: ubuntu-latest
      target: x86_64-unknown-linux-gnu
  aarch64-apple-darwin:
    uses: ./.github/workflows/package.yml
    with:
      runs_on: macos-latest
      target: aarch64-apple-darwin
  x86_64-apple-darwin:
    uses: ./.github/workflows/package.yml
    with:
      runs_on: macos-latest
      target: x86_64-apple-darwin
  x86_64-pc-windows-msvc:
    uses: ./.github/workflows/package.yml
    with:
      runs_on: windows-latest
      target: x86_64-pc-windows-msvc
      ext: .exe
  x86_64-pc-windows-gnu:
    uses: ./.github/workflows/package.yml
    with:
      runs_on: windows-latest
      target: x86_64-pc-windows-gnu
      ext: .exe
